version: '3.3'

services:
  magic-cards:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    devices:
      - "/dev/input/event0:/dev/input/event0"
    volumes:
      - ./config:/usr/src/app/config
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules/
      - /usr/src/app/server/public/
      - ./scanner:/usr/src/app/scanner
      - /usr/src/app/scanner/node_modules/
