#!/bin/sh

# script/bootstrap: Set up project dependencies

set -e

cd "$(dirname "$0")/.."

echo "Installing dependencies..."

npm install yarn -g
npm install concurrently@5.3.0 -g

yarn

cd server
yarn

cd ..

cd client
yarn

cd ..

cd scanner
yarn
